# Generated by Django 4.1.3 on 2023-01-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myclient", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="stock",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="service",
            new_name="specialization",
        ),
        migrations.AlterField(
            model_name="gallery",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="something about gallery (Images or Files)",
                max_length=1000,
                null=True,
            ),
        ),
    ]
