# Generated by Django 4.1.3 on 2023-01-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_end_at_customuser_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logo/"),
        ),
    ]
